version: '3.4'

services:
  klipper:
    image: gucio1200/klipper:latest
    container_name: klipper
#    privileged: true
#    depends_on:
#      - mcu
    restart: unless-stopped
    volumes:
      - klipper:/home/klippy/klipper
      - ./runtime/config:/home/klippy/.config
      - ./runtime/logs:/logs
      - ./runtime/gcode_files:/home/klippy/gcode_files
      - ./runtime/tmp:/tmp
      - /dev:/dev
    devices:
      - /dev/klipper:/dev/klipper

#  mcu:
#    image: gucio1200/klipper:latest
#    container_name: mcu
#    privileged: true
#    restart: unless-stopped
#    command: /home/klippy/klipper/out_linux/klipper.elf
#    volumes:
#      - ./runtime/config:/home/klippy/.config
#      - ./runtime/logs:/logs
#      - ./runtime/gcode_files:/home/klippy/gcode_files
#      - ./runtime/tmp:/tmp
#      - /dev:/dev

  moonraker:
    image: gucio1200/moonraker:latest
    container_name: moonraker
    privileged: true
    ports:
      - 7125:7125
    restart: unless-stopped
    depends_on:
      - klipper
#      - mcu
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:7125/server/info"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - klipper:/home/klippy/klipper
      - moonraker:/home/klippy/moonraker
      - klipperscreen:/home/klippy/klipperscreen
      - ./runtime/.moonraker_database:/home/klippy/.moonraker_database
      - ./runtime/config:/home/klippy/.config
      - ./runtime/logs:/logs
      - ./runtime/gcode_files:/home/klippy/gcode_files
      - ./runtime/tmp:/tmp
      - /dev:/dev

  klipperscreen:
    image: gucio1200/klipperscreen:latest
    build:
      dockerfile: ./klipperscreen/Dockerfile
      context: .
    environment:
     - DISPLAY=unix:0.0
    user: klippy
    container_name: klipperscreen
    restart: unless-stopped
    depends_on:
      moonraker:
        condition: service_healthy
    links:
      - moonraker:moonraker
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://moonraker:7125/printer/info"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - klipperscreen:/home/klippy/KlipperScreen
      - ./runtime/config/KlipperScreen.conf:/home/klippy/KlipperScreen.conf

  fluidd:
    image: cadriel/fluidd:latest
    container_name: fluidd
    ports:
      - 8010:80
    restart: unless-stopped
    depends_on:
      moonraker:
        condition: service_healthy
    links:
      - moonraker:moonraker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fluidd.rule=PathPrefix(`/`)"

#  mainsail:
#    image: gucio1200/mainsail:latest
#    build:
#      dockerfile: Dockerfile
#      context: frontend
#      args:
#        FRONTEND_ZIP_URL: https://github.com/meteyou/mainsail/releases/latest/download/mainsail.zip
#    container_name: mainsail
#    restart: unless-stopped
#    ports:
#      - 8011:80
#    depends_on:
#      moonraker:
#        condition: service_healthy
#    links:
#      - moonraker:moonraker

  ustreamer:
    image: gucio1200/ustreamer:latest
    build:
      dockerfile: ./ustreamer/Dockerfile
      context: .
    container_name: ustreamer
    restart: unless-stopped
    command: ./ustreamer --host=0.0.0.0 --slowdown --format=mjpeg -r 1280x960 --buffers=3 --drop-same-frames=30 -q 100
    ports:
      - 8080:8080
    devices:
      - /dev/video0:/dev/video0

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runtime/portainer:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8012:80"
    volumes:
      - ./runtime/logs:/usr/share/nginx/html/logs
      - ./runtime/gcode_files:/usr/share/nginx/html/gcode_files
      - ./runtime/tmp:/usr/share/nginx/html/tmp
      - ./runtime/empty:/usr/share/nginx/html
      - ./runtime/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/logs`)"
      - "traefik.http.routers.nginx.middlewares=stripprefix-nginx@docker"
      - "traefik.http.middlewares.stripprefix-nginx.stripprefix.prefixes=/logs"

  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: unless-stopped
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8088:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  klipper:
  klipperscreen:
  moonraker:
