
---

name: Build Fluidd
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - 'master'
  workflow_dispatch:
  repository_dispatch:
    types: [fluidd]
  
      
jobs:
  build_fluidd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: fluidd-core/fluidd
          ref: develop
 
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: fluidd
          path: |
            dist
          retention-days: 5

#  docker:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@master
#        with:
#          platforms: all

#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@master

#      - name: Login to DockerHub
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Build
#        uses: docker/build-push-action@v2
#        with:
#          builder: ${{ steps.buildx.outputs.name }}
#          context: mainsail
#          file: ./mainsail/Dockerfile
#          platforms: linux/arm64
#          push: true
#          tags: gucio1200/mainsail:latest
#          build-args: |
#            FRONTEND_ZIP_URL=https://github.com/meteyou/mainsail/releases/latest/download/mainsail.zip
