---

name: Check remote
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  schedule:
    - cron: "42 13 * * 0,2,5"
      
jobs:
  check:
    strategy:
      matrix:
        repos:
          - KevinOConnor/klipper
          - jordanruthe/KlipperScreen
          - meteyou/mainsail
          - Arksine/moonraker
          - pikvm/ustreamer
          
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v2
        with:
          repository:  ${{ matrix.repos }}
          fetch-depth: 0
          
