---

name: Check remote
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  schedule:
    - cron: "42 13 * * 0,2,5"
      
jobs:
  check:
    strategy:
      matrix:
        repos:
          - https://github.com/KevinOConnor/klipper.git
          - https://github.com/jordanruthe/KlipperScreen.git
          - https://github.com/meteyou/mainsail.git
          - https://github.com/Arksine/moonraker.git
          - https://github.com/pikvm/ustreamer.git
          
    runs-on: ubuntu-latest
    steps:
        
      - uses: mego22/actions-git-sha@main
        id: remote_sha
        with:
          repo: "${{ matrix.repos }}"
          
      - name: Print sha
        run: echo "The sha is ${{ steps.remote_sha.outputs.sha }} for repo ${{ steps.remote_sha.input.repo }}"
