---

name: Check remote
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  schedule:
    - cron: "42 13 * * 0,2,5"
      
jobs:
  check:
    strategy:
      matrix:
        repos:
          - KevinOConnor/klipper
          - jordanruthe/KlipperScreen
          - meteyou/mainsail
          - Arksine/moonraker
          - pikvm/ustreamer
          
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v2
        with:
          repository:  ${{ matrix.repos }}
          fetch-depth: 0
          
      - name: Check if Updated
        run: |
         git log --format=format:%s --first-parent --since='24 hours ago'
        shell: bash
          
      - name: Check if Updated
        run: |
         if [ $(git log --format=format:%s --first-parent --since='24 hours ago' | wc -l) -gt 0 ]; 
         then 
           echo "UPGRADE=true" >> $GITHUB_ENV
         fi
        shell: bash
        
      - name: Check if Updated
        run: env
        shell: bash
        
      - name: Need to update
        run: |
         echo ${{ matrix.repos }}
        shell: bash
        if: env.UPGRADE
        
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: my-event

          
