---

name: Check remote
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  schedule:
    - cron: "42 13 * * 0,2,5"
      
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: mego22/actions-git-sha@main
        id: remote_sha
        with:
          repo: "https://github.com/KevinOConnor/klipper.git"
          
      - name: Print sha
        run: echo "The sha is ${{ steps.remote_sha.outputs.sha }}"
